### ISSUE TITLE
Could not create an instance of type Jojatekok.PoloniexAPI.WalletTools.IBalance. Type is an interface or abstract class and cannot be instantiated

### ISSUE THREAD

**Issue by nickmccombewn** [Jojatekok/PoloniexApi.Net#7]
Can't get wallet balance using:
var x = await polo_client.Wallet.GetBalancesAsync(); 

This gives an error:
Error getting wallet:Could not create an instance of type Jojatekok.PoloniexAPI.WalletTools.IBalance. Type is an interface or abstract class and cannot be instantiated. Path '1CR.available', line 1, position 20.

**Comment by loginmanish** [comment]
Please use Balance instead of IBalance to deserialize.

**Comment by turgayacar** [comment]
I use bellow but nothing change. push this error.
IDictionary<string, Balance> balances =(IDictionary<string, Balance>) await PoloClient.Wallet.GetBalancesAsync();
